env:
  global:
    - secure: FHEMPz3hG2avo2Oxm11E89uBJRQSqeXjhC02IHdb4ItPH7zQnkaZJZ8GmY9hZlcsli0OJeglmCZ3KBeN3369ZArFq2QFkU2AKMm8AZ9tmJaRIF/k2eYfFs9C7cYDg7/Z8hGyu0sfcOfdNK7fdvJ2hvSuMJijYzcT+aIUPUl4VCM=
    - secure: JHvlyLHiD+Kmrt6HcPB41PgbXPD8b81DJ/MGauxEkUSuDrFurwJ8w+ELUaG3QfFmHlsNcN5u9IEmSp8sh6Mg7MgV1okyda+EKpVVLOcJns7QF3/xY0aYnMz9/8F/YkrbHMm2kQgT6+fouBAhaVD7GIxXrP/Esq2TzOC7pMpx1ns=
addons:
  sauce_connect: true
language: node_js
node_js:
  - 0.10
before_script:
  - npm install -g grunt-cli
script:
  - grunt yadda nightwatch:saucelabs
