env:
  global:
  - secure: fjmJ3/iL71bkTN0z/6o/YQr2T2xpsT/kOKt6O2TK/4jZ1qX5O+yiIHnIMZTG5FrqwxrWLJ0n0ArTzYEJNcnlyRGsGsrD2frNX9q06zbYEfNIj3ifxh/jRz8t8kfJr4VgpHPQx5NMMCqhk/1QKEglRN0775ILUhKynjmKlWsujps=
  - secure: hJu4M/d87RRdmB2J5PziDv019SO8y8nxiIgC+n+DkeavcmDx7u9bD+mXNcrnD6sQaBVqycN+5NhumaCkTZWRnzaGjcG0u7Kr1l174GuAg414MrNTIDTinW2waZJpHaFLn0CO/6N0ZmbcOZO32qmrI3W+rXLoHMKAPT8v+wPccSc=
addons:
  sauce_connect: true
language: node_js
node_js:
- 0.1
- 0.12
- iojs
before_script:
- npm install -g grunt-cli
script:
- grunt y2nw nightwatch:saucelabs
